spring:
  application:
    name: hami-chau
  mvc:
    servlet:
      path: /hamichau

  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 2MB
      file-size-threshold: 0

server:
  port: 8081

uploadDir: D:/test/

#sqlplus / as sysdba
#ALTER USER c##hamichhau IDENTIFIED BY hami;

